In [6]:
from bs4 import BeautifulSoup
import requests

1


In [55]:
import os
os.listdir('supermarkets')


['.DS_Store',
 'supermarkets.json',
 'supermarkets.csv',
 'supermarkets-semi-colons.txt',
 'supermarkets.xlsx',
 'supermarkets-commas.txt']

In [47]:
from geopy.geocoders import ArcGIS
nom = ArcGIS()

In [8]:
import pandas
df1 = pandas.read_json("supermarkets/supermarkets.json")
df1

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [13]:
df2=pandas.read_json("supermarkets/supermarkets.json")
df2.set_index("ID")

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [15]:
df3 = pandas.read_excel("supermarkets/supermarkets.xlsx", sheet_name=0)
df3

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [22]:
df4=pandas.read_csv("supermarkets/supermarkets-commas.txt")
df4

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [24]:
df5=pandas.read_csv("supermarkets/supermarkets-semi-colons.txt", sep=";")
df5

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [27]:
df7=pandas.read_json("supermarkets/supermarkets.json")
df7

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [58]:
df = pandas.read_csv("supermarkets/supermarkets.csv")


ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [53]:
n=nom.geocode("4676 Prescot Dr, Bethel Park, PA 15102")
type(n)

geopy.location.Location

In [61]:
df['Address'] = df['Address'] + ", " + df['City'] + ", " + df['State'] + ", " + df['Country']
df['Coordinates'] = df['Address'].apply(nom.geocode)
df.Coordinates

0    (3666 21st St, San Francisco, California, 9411...
1    (735 Dolores St, San Francisco, California, 94...
2    (332 Hill St, San Francisco, California, 94114...
3    (3995 23rd St, San Francisco, California, 9411...
4    (1056 Sanchez St, San Francisco, California, 9...
5    (551 Alvarado St, San Francisco, California, 9...
Name: Coordinates, dtype: object

In [65]:
df['Latitude'] = df['Coordinates'].apply(lambda x: x.latitude if x != None else None)
df['Longitude'] = df['Coordinates'].apply(lambda x: x.longitude if x != None else None)

df

ID                                            Address           City  \
0   1  3666 21st St, San Francisco, CA 94114, USA, Sa...  San Francisco   
1   2  735 Dolores St, San Francisco, CA 94119, USA, ...  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, ...  San Francisco   
3   4  3995 23rd St, San Francisco, CA 94114, USA, Sa...  San Francisco   
4   5  1056 Sanchez St, San Francisco, California, US...  San Francisco   
5   6  551 Alvarado St, San Francisco, CA 94114, USA,...  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates   Latitude   Longitude  
0  (3666 21st St, San Francisco, California, 9411...  37.756632 -122.429411  
1  (735 Dolores St, San Francisco, California, 94...  37.757829 -122.425373  
2  (332 Hill St, San Francisco, California, 94114...  37.755845 -122.428813  
3  (3995 23rd St, San Francisco, California, 9411...  37.752921 -122.431703  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752132 -122.430006  
5  (551 Alvarado St, San Francisco, California, 9...  37.753582 -122.433234

In [16]:
import numpy
import cv2

In [18]:
im_g = cv2.imread("smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [10]:
cv2.imwrite("newsmallgray.png", im_g)

array([list([123, 12, 32, 55, 21]), list([]), list([])], dtype=object)

In [35]:
ims = numpy.hstack((im_g, im_g))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [38]:
lst=numpy.hsplit(ims,5)
lst

[array([[187, 158],
        [198, 125],
        [209, 134]], dtype=uint8),
 array([[104, 121],
        [255, 255],
        [255,  97]], dtype=uint8),
 array([[143, 187],
        [147, 198],
        [182, 209]], dtype=uint8),
 array([[158, 104],
        [125, 255],
        [134, 255]], dtype=uint8),
 array([[121, 143],
        [255, 147],
        [ 97, 182]], dtype=uint8)]